services:
  frontend:
    build: 
       context: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - todo-api-service
    networks:
      - layer1
  todo-api-service: 
    build: 
      context: ./backend
    env_file:
      - .env
    networks: 
      - layer1
      - layer2
    depends_on:
      - database
  database:
    image: mysql:8.0.30-debian
    ports:
    - "3307:3306"
    env_file:
      - .env
    volumes:
    - ./sqlscripts:/docker-entrypoint-initdb.d
    - dbdata:/var/lib/mysql
    networks:
      - layer2
volumes:
  dbdata:

networks: 
  layer1:
  layer2: